# Generated by Django 3.0.6 on 2020-06-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200601_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='instagram',
        ),
        migrations.AddField(
            model_name='equipe',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, verbose_name='Linkedin'),
        ),
    ]
